services:
  db:
    image: postgres:15-alpine
    container_name: evorise_db
    environment:
      POSTGRES_USER: ${DB_USERNAME:-evorise}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_DATABASE:-evorise}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]   # persiste em dev
    ports:
      - "6379:6379"    # opcional; só precisa se acessar do host
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 10      

  app:
    build: .
    container_name: evorise_api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: ${API_PORT:-3000}
      DB_DIALECT: postgres
      DB_HOST: db
      DB_PORT: "5432"
      DB_USERNAME: ${DB_USERNAME:-evorise}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      DB_DATABASE: ${DB_DATABASE:-evorise}
      GOOGLE_AUTH_ENABLED: ${GOOGLE_AUTH_ENABLED:-false}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL:-}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID:-}
      GOOGLE_AUTH_URI: ${GOOGLE_AUTH_URI:-}
      GOOGLE_TOKEN_URI: ${GOOGLE_TOKEN_URI:-}
      GOOGLE_CERTS_URI: ${GOOGLE_CERTS_URI:-}
      REDIS_URL: redis://redis:6379/0
      SEQUELIZE_SEEDER_PATH: ./src/database/seeds      
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data:
  redis_data:
